In [20]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px
import nltk
import os 
import json
import spacy
import warnings
import joblib
from tqdm import tqdm
import gensim
from nltk.corpus import stopwords
from nltk.stem.wordnet import WordNetLemmatizer
from nltk.stem import SnowballStemmer

warnings.filterwarnings('ignore')
nlp = spacy.load('en_core_web_trf', disable=['parser', 'ner'])
stop = stopwords.words('english')
stemmer = SnowballStemmer('english')

platform_df=pd.read_csv('Kickstarter_only/before_creator.csv')

In [21]:
data=[]
with open(r'Kickstarter_only/creator_data.txt','r', encoding='utf-8') as f:
    for line in f:
        data.append([line.strip()])

In [22]:
creator_df = pd.DataFrame([x[0].split(',') for x in data][1:])

In [23]:
creator_df.loc[332,1] = creator_df.loc[332,2] 
creator_df.loc[332,2] = creator_df.loc[332,3] 
creator_df.loc[646,2] = creator_df.loc[646,2] +','+creator_df.loc[646,3]  

creator_df[creator_df.loc[:,3].notnull()]

                 0           1                         2                 3
332      9 created  109 backed           Benjamin Kepner   Benjamin Kepner
646  First created    0 backed   William H.  Boling, Jr.               Jr.

In [24]:
creator_df.drop(3, inplace=True, axis=1)

In [25]:
creator_df.duplicated().sum()

np.int64(68)

In [26]:
creator_df = creator_df.rename(columns={0:'num_projects',1:'num_backed',2:'verified'})

In [27]:
creator_df['num_projects'] = creator_df.num_projects.str.split(' ').apply(lambda x: x[0])
creator_df['num_projects'] = creator_df.num_projects.str.replace('First', '1')
creator_df['num_projects'] = creator_df.num_projects.astype(int)

In [28]:
creator_df['num_backed'] = creator_df.num_backed.str.strip().str.split(' ').apply(lambda x:x[0]).astype(int)

In [29]:
platform_df.drop('Unnamed: 0', axis=1, inplace=True)

In [30]:
platform_df

,idx,collected,goal_amount,num_backers,category,duration,pledge_types,donate,creator,project_we_love,success,start_month,start_day,population,country
0,0,8.600799,8.496990,66,games,30,7.0,0.0,Janos Stone,1.0,1,6,4,11.973093,MA
1,2,11.626750,10.886128,"1,462",games,30,9.0,0.0,Cherrymochi Game Studio,1.0,1,7,1,15.936166,Japan
2,3,12.960635,10.819778,918,design,30,4.0,0.0,Moment,1.0,1,6,1,13.436372,WA
3,4,9.030855,11.021151,93,food,22,12.0,0.0,Akwasi Brenya-Mensa,1.0,0,6,6,15.837972,UK
4,5,11.866416,9.903488,"1,047",comics,34,8.0,0.0,Adam Lawson,1.0,1,6,1,11.564749,CA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1103,2463,10.303136,10.126631,640,food,30,14.0,0.0,Ilana Kruger + Kara Cohen,1.0,1,7,1,14.648708,NY
1104,2466,10.922389,10.126631,"1,365",comics,19,8.0,0.0,Lucy Bellwood,1.0,1,7,2,13.357133,OR
1105,2467,9.280985,9.210340,82,journalism,28,10.0,0.0,Elisa Da Prato,1.0,1,7,1,14.648708,NY
1106,2472,10.500372,9.210340,445,food,30,12.0,0.0,Dachi Tea Co.,1.0,1,7,6,12.096297,RI
1107,2473,9.539693,9.287301,68,design,30,10.0,0.0,walter mason,1.0,1,7,5,15.047007,Germany

In [31]:
pd.concat([platform_df,creator_df], axis=1)

,idx,collected,goal_amount,num_backers,category,duration,pledge_types,donate,creator,project_we_love,success,start_month,start_day,population,country,num_projects,num_backed,verified
0,0,8.600799,8.496990,66,games,30,7.0,0.0,Janos Stone,1.0,1,6,4,11.973093,MA,2,10,janos stone
1,2,11.626750,10.886128,"1,462",games,30,9.0,0.0,Cherrymochi Game Studio,1.0,1,7,1,15.936166,Japan,2,0,Maho Williams
2,3,12.960635,10.819778,918,design,30,4.0,0.0,Moment,1.0,1,6,1,13.436372,WA,7,16,Marc Barros
3,4,9.030855,11.021151,93,food,22,12.0,0.0,Akwasi Brenya-Mensa,1.0,0,6,6,15.837972,UK,2,1,Akwasi Brenya-Mensa
4,5,11.866416,9.903488,"1,047",comics,34,8.0,0.0,Adam Lawson,1.0,1,6,1,11.564749,CA,3,88,Adam Lawson
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1103,2463,10.303136,10.126631,640,food,30,14.0,0.0,Ilana Kruger + Kara Cohen,1.0,1,7,1,14.648708,NY,1,3,Kara Cohen
1104,2466,10.922389,10.126631,"1,365",comics,19,8.0,0.0,Lucy Bellwood,1.0,1,7,2,13.357133,OR,3,91,Lucy Bellwood
1105,2467,9.280985,9.210340,82,journalism,28,10.0,0.0,Elisa Da Prato,1.0,1,7,1,14.648708,NY,1,0,Elisa Da Prato
1106,2472,10.500372,9.210340,445,food,30,12.0,0.0,Dachi Tea Co.,1.0,1,7,6,12.096297,RI,2,4,Nicholas Palumbo
1107,2473,9.539693,9.287301,68,design,30,10.0,0.0,walter mason,1.0,1,7,5,15.047007,Germany,3,5,Walter Mason

In [32]:
person = creator_df.verified.str.strip().str.lower() == platform_df.creator.str.strip().str.lower()
person.astype(int)

0       1
1       0
2       0
3       1
4       1
       ..
1103    0
1104    1
1105    1
1106    0
1107    1
Length: 1108, dtype: int64

In [33]:
team = ~person
team

0       False
1        True
2        True
3       False
4       False
        ...
1103     True
1104    False
1105    False
1106     True
1107    False
Length: 1108, dtype: bool

In [34]:
platform_df['Person'] = person.astype('int8')
platform_df['Team'] = team.astype('int8')

In [35]:
platform_df.drop('creator', axis=1, inplace=True)

In [36]:
final_data = pd.concat([platform_df,creator_df], axis=1)

In [37]:
final_data

,idx,collected,goal_amount,num_backers,category,duration,pledge_types,donate,project_we_love,success,start_month,start_day,population,country,Person,Team,num_projects,num_backed,verified
0,0,8.600799,8.496990,66,games,30,7.0,0.0,1.0,1,6,4,11.973093,MA,1,0,2,10,janos stone
1,2,11.626750,10.886128,"1,462",games,30,9.0,0.0,1.0,1,7,1,15.936166,Japan,0,1,2,0,Maho Williams
2,3,12.960635,10.819778,918,design,30,4.0,0.0,1.0,1,6,1,13.436372,WA,0,1,7,16,Marc Barros
3,4,9.030855,11.021151,93,food,22,12.0,0.0,1.0,0,6,6,15.837972,UK,1,0,2,1,Akwasi Brenya-Mensa
4,5,11.866416,9.903488,"1,047",comics,34,8.0,0.0,1.0,1,6,1,11.564749,CA,1,0,3,88,Adam Lawson
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1103,2463,10.303136,10.126631,640,food,30,14.0,0.0,1.0,1,7,1,14.648708,NY,0,1,1,3,Kara Cohen
1104,2466,10.922389,10.126631,"1,365",comics,19,8.0,0.0,1.0,1,7,2,13.357133,OR,1,0,3,91,Lucy Bellwood
1105,2467,9.280985,9.210340,82,journalism,28,10.0,0.0,1.0,1,7,1,14.648708,NY,1,0,1,0,Elisa Da Prato
1106,2472,10.500372,9.210340,445,food,30,12.0,0.0,1.0,1,7,6,12.096297,RI,0,1,2,4,Nicholas Palumbo
1107,2473,9.539693,9.287301,68,design,30,10.0,0.0,1.0,1,7,5,15.047007,Germany,1,0,3,5,Walter Mason

## Social Media data - redo

In [39]:
current_dir = 'Kickstarter_only/'

post_data = pd.read_csv(current_dir + '2022-07-22-09-31-10-IST-feed-download.csv')
print(post_data.shape)

post_data = post_data[post_data.loc[:, "Page Name"] == 'Kickstarter'].reset_index()
post_data = post_data.iloc[final_data.idx, :]
post_data['final_data_idx'] = final_data.index.to_list()
print(post_data.shape)
post_data.drop_duplicates(inplace=True, subset=['Message'], keep='last')
print(post_data.shape)

post_data.columns = [x.lower().replace(' ','_') for x in post_data.columns.to_list()]
post_data.drop(['user_name', 'facebook_id', 'page_category', 'page_admin_top_country',
                'overperforming_score_(weighted__—__likes_1x_shares_1x_comments_1x_love_1x_wow_1x_haha_1x_sad_1x_angry_1x_care_1x_)'],
                 axis=1, inplace=True)
 

max_likes, max_comments, max_shares = 541,373,233
post_data = post_data[post_data.likes<max_likes].reset_index(drop=True)
post_data = post_data[post_data.comments<max_comments].reset_index(drop=True)
post_data = post_data[post_data.shares<max_shares].reset_index(drop=True)

#Calculating Age of the post and the page
post_data.page_created = pd.to_datetime(post_data.page_created, dayfirst=True)
post_data.post_created = pd.to_datetime(post_data['post_created'].str.replace('IST', ''))
post_data['current_date'] = pd.to_datetime('2022-07-22 09:31:10') 
post_data['post_age'] = (post_data.current_date - post_data.post_created).dt.days
post_data['page_age'] = (post_data.current_date - post_data.page_created).dt.days

#grouping public engagements into two broad categories
post_data['positive_reactions'] = post_data['love'] + post_data['haha'] + post_data['wow'] + post_data['care']
post_data['negative_reactions'] = post_data['sad'] + post_data['angry']
post_data['emoji_reactions'] = post_data['positive_reactions'] + post_data['negative_reactions'] + post_data['likes']
print(post_data.shape)

(9527, 39)
(1108, 41)
(1108, 41)
(1097, 42)

In [40]:
post_data.rename(columns = {'index':'idx'}, inplace=True)

In [42]:
processed_csv = pd.read_csv("Original_dataset/processed_data.csv")
processed_csv = processed_csv[processed_csv.page_name == 'Kickstarter']
processed_csv.rename(columns={'index':'idx'}, inplace=True)
final_list = []
for i in post_data.idx.to_list():
    if i in processed_csv.original_index.to_list():
        final_list.append(i)
    
print(len(final_list))

post_data = post_data[post_data.idx.isin(final_list)]
processed_csv = processed_csv[processed_csv.original_index.isin(final_list)]

processed_csv.drop('original_index', axis=1, inplace=True)
processed_csv.reset_index(drop=True, inplace=True)
processed_csv.columns = ['fb_'+x for x in processed_csv.columns.to_list()]

processed_csv

947

,fb_page_name,fb_likes_at_posting,fb_followers_at_posting,fb_type,fb_likes,fb_comments,fb_shares,fb_post_views,fb_readability,fb_readability_lix,...,fb_positive_reactions,fb_negative_reactions,fb_topic_0,fb_topic_1,fb_topic_2,fb_topic_3,fb_topic_4,fb_topic_5,fb_topic_6,fb_topic_7
0,Kickstarter,1589842,1587991,link,1,1,0,2,8.267143,48.595238,...,1,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.951302
1,Kickstarter,1589866,1588006,link,5,2,0,5,8.475000,33.000000,...,0,0,0.000000,0.000000,0.000000,0.000000,0.945262,0.000000,0.000000,0.000000
2,Kickstarter,1589901,1588019,link,10,2,1,12,4.836818,33.727273,...,2,0,0.000000,0.000000,0.268851,0.000000,0.000000,0.000000,0.689443,0.000000
3,Kickstarter,1589715,1587803,link,3,1,0,4,15.900000,61.666667,...,0,1,0.000000,0.000000,0.348670,0.000000,0.000000,0.613742,0.000000,0.000000
4,Kickstarter,1589715,1587803,link,3,5,1,5,14.239500,45.000000,...,1,1,0.558022,0.000000,0.310321,0.000000,0.000000,0.098730,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
942,Kickstarter,1535819,1507542,video,102,23,49,31739,37.896842,50.578947,...,12,0,0.015655,0.390595,0.015630,0.015632,0.515601,0.015628,0.015631,0.015628
943,Kickstarter,1535733,1507458,video,72,1,15,14013,24.544375,44.125000,...,4,0,0.000000,0.000000,0.156273,0.081164,0.720869,0.000000,0.000000,0.000000
944,Kickstarter,1535733,1507458,video,14,1,2,10616,31.478333,42.333333,...,2,0,0.015634,0.332804,0.015629,0.015665,0.015637,0.015651,0.015630,0.573349
945,Kickstarter,1535625,1507353,link,16,1,3,17,5.669792,36.583333,...,1,0,0.945267,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
946,Kickstarter,1535625,1507353,video,105,2,17,24415,26.268000,32.500000,...,9,0,0.012518,0.193765,0.012510,0.412685,0.231268,0.112226,0.012514,0.012514

In [43]:
processed_csv.columns

Index(['fb_page_name', 'fb_likes_at_posting', 'fb_followers_at_posting',
       'fb_type', 'fb_likes', 'fb_comments', 'fb_shares', 'fb_post_views',
       'fb_readability', 'fb_readability_lix', 'fb_entropy_scores',
       'fb_perplexity_scores', 'fb_fear', 'fb_anger', 'fb_anticip', 'fb_trust',
       'fb_surprise', 'fb_positive', 'fb_negative', 'fb_sadness', 'fb_disgust',
       'fb_joy', 'fb_entities_identified', 'fb_post_sponsored', 'fb_post_age',
       'fb_page_age', 'fb_positive_reactions', 'fb_negative_reactions',
       'fb_topic_0', 'fb_topic_1', 'fb_topic_2', 'fb_topic_3', 'fb_topic_4',
       'fb_topic_5', 'fb_topic_6', 'fb_topic_7'],
      dtype='object')

In [44]:
final_data = final_data.iloc[post_data.final_data_idx.values, :].drop('idx', axis=1).reset_index(drop=True)

In [45]:
pd.concat([final_data, processed_csv], axis=1).to_csv('Kickstarter_only/final_data.csv', index=False)

In [46]:
df = pd.read_csv('Kickstarter_only/final_data.csv')
df

,collected,goal_amount,num_backers,category,duration,pledge_types,donate,project_we_love,success,start_month,...,fb_positive_reactions,fb_negative_reactions,fb_topic_0,fb_topic_1,fb_topic_2,fb_topic_3,fb_topic_4,fb_topic_5,fb_topic_6,fb_topic_7
0,8.600799,8.496990,66,games,30,7.0,0.0,1.0,1,6,...,1,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.951302
1,11.626750,10.886128,"1,462",games,30,9.0,0.0,1.0,1,7,...,0,0,0.000000,0.000000,0.000000,0.000000,0.945262,0.000000,0.000000,0.000000
2,12.960635,10.819778,918,design,30,4.0,0.0,1.0,1,6,...,2,0,0.000000,0.000000,0.268851,0.000000,0.000000,0.000000,0.689443,0.000000
3,10.374272,10.308953,203,film_Video,30,13.0,0.0,1.0,1,6,...,0,1,0.000000,0.000000,0.348670,0.000000,0.000000,0.613742,0.000000,0.000000
4,9.542446,8.804775,258,comics,31,16.0,0.0,1.0,1,6,...,1,1,0.558022,0.000000,0.310321,0.000000,0.000000,0.098730,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
942,10.303136,10.126631,640,food,30,14.0,0.0,1.0,1,7,...,12,0,0.015655,0.390595,0.015630,0.015632,0.515601,0.015628,0.015631,0.015628
943,10.922389,10.126631,"1,365",comics,19,8.0,0.0,1.0,1,7,...,4,0,0.000000,0.000000,0.156273,0.081164,0.720869,0.000000,0.000000,0.000000
944,9.280985,9.210340,82,journalism,28,10.0,0.0,1.0,1,7,...,2,0,0.015634,0.332804,0.015629,0.015665,0.015637,0.015651,0.015630,0.573349
945,10.500372,9.210340,445,food,30,12.0,0.0,1.0,1,7,...,1,0,0.945267,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
946,9.539693,9.287301,68,design,30,10.0,0.0,1.0,1,7,...,9,0,0.012518,0.193765,0.012510,0.412685,0.231268,0.112226,0.012514,0.012514